controllers/KursController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Kurs;
use app\models\KursSearch;
use app\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\lib\ArrayHelper;

/**
 * KursController implements the CRUD actions for Kurs model.
 */
class KursController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Kurs models.
     * @return mixed
     */
    public function actionIndex() {

        if (Yii::$app->user->isGuest) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }

        $searchModel = new KursSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (!\app\models\User::isAdmin()) {
            $user = Yii::$app->user->identity;
            $kursIds = array_map(function($m) {
                return $m->id_kurs;
            }, $user->getKurs()->all());
            $dataProvider->query->andWhere(['id_kurs' => $kursIds]);
        }
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all public Kurs models.
     * @return mixed
     */
    public function actionPublic() {
        $searchModel = new KursSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $query = $dataProvider->query;
        $rowsPerPage = Yii::$app->params['rowsPerPage'];
        $query->andWhere(['visible' => 1]);

        $request = array_merge(Yii::$app->request->post(), Yii::$app->request->queryParams);

        $start = isset($request['start']) ? ( (int) $request['start'] ) : 0;
        return $this->render('public', [
                    'searchModel' => $searchModel,
                    'rows' => $query->limit($rowsPerPage)->offset($start)->all(),
                    'request' => $request
        ]);
    }

    /**
     * Displays a single Kurs model.
     * @param string $id
     * @return mixed
     */
    public function actionDetails($id) {
        $kurs = $this->findModel($id);
        if (!$kurs->visible) {
            throw new NotFoundHttpException(Yii::$app->lang->t('Page not found'));
        }
        return $this->render('details', [
                    'model' => $kurs,
        ]);
    }

    /**
     * Displays a single Kurs model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id) {
        $kurs = $this->findModel($id);
        if (!$kurs->isKursManager()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }
        return $this->render('view', [
                    'model' => $kurs,
        ]);
    }

    /**
     * Creates a new Kurs model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        if (!\app\models\User::isAdmin()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin rights required'));
        }
        $model = new Kurs();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_kurs]);
        } else {
            $userOptions = ArrayHelper::map(User::find()->all(), 'userId', ['userPIB', 'userLogin']);
            return $this->render('create', [
                        'model' => $model,
                        'userOptions' => $userOptions,
            ]);
        }
    }

    /**
     * Updates an existing Kurs model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $kurs = $this->findModel($id);
        if (!$kurs->isKursManager()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }
        if ($kurs->load(Yii::$app->request->post()) && $kurs->save()) {
            return $this->redirect(['view', 'id' => $kurs->id_kurs]);
        } else {


            $userOptions = ArrayHelper::map(User::find()->all(), 'userId', ['userPIB', 'userLogin']);
            return $this->render('update', [
                        'model' => $kurs,
                        'userOptions' => $userOptions,
            ]);
        }
    }

    /**
     * Deletes an existing Kurs model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id) {
        $kurs = $this->findModel($id);
        if (!\app\models\User::isAdmin()){
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin rights required'));
        }
        $kurs->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Kurs model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Kurs the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Kurs::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

controllers/StudentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Group;
use app\models\Student;
use app\models\StudentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use app\lib\ArrayHelper;

/**
 * StudentController implements the CRUD actions for Student model.
 */
class StudentController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Student models.
     * @return mixed
     */
    public function actionIndex($id_group) {
        $group = Group::findOne($id_group);
        if (!$group) {
            throw new NotFoundHttpException(Yii::$app->lang->t('Page not found'));
        }
        $kurs = $group->idKurs;
        if (!$kurs->isKursManager()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }

        $searchModel = new StudentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere([ 'id_group' => $id_group,]);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                    'group' => $group,
                    'kurs' => $kurs
        ]);
    }

    public function actionDownload($id_group) {

        $group = Group::findOne($id_group);
        if (!$group) {
            throw new NotFoundHttpException(Yii::$app->lang->t('Page not found'));
        }
        $kurs = $group->idKurs;
        if (!$kurs->isKursManager()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }

        $dir = Yii::getAlias("@webroot/uploads/kurs{$kurs->id_kurs}");
        if (!file_exists($dir)) {
            mkdir($dir);
        }

        $destination = "{$dir}/group{$group->id_group}.zip";
        if (file_exists($destination)) {
            unlink($destination);
        }

        // create list
        $searchModel = new StudentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $query = $dataProvider->query;
        $query->andFilterWhere([ 'id_group' => $id_group,]);
        $students = $query->all();

        $table = "{$dir}/group{$group->id_group}.html";
        if (file_exists($table)) {
            unlink($table);
        }
        $csv = "{$dir}/group{$group->id_group}.csv";
        if (file_exists($csv)) {
            unlink($csv);
        }
        $files = [];
        $rows = [];
        $colNames = [];

        
        $colNames['id_stud'] = Yii::$app->lang->t('id_stud');
        $colNames['firstName'] = Yii::$app->lang->t('firstName');
        $colNames['middleName'] = Yii::$app->lang->t('middleName');
        $colNames['lastName'] = Yii::$app->lang->t('lastName');
        $colNames['email'] = 'email';
        
        
        $blank = $group->blankAnkety();
        $anketa = new \app\lib\ShowAnketa('anketa');
        $postedAnketaData = $anketa->in($blank, [], []);
        foreach($postedAnketaData as $elm){
            if (!isset($colNames[$elm['name']])) {
                $colNames[$elm['name']] = $elm['label'];
            }
        }
        
        foreach ($students as $student) {
            $colValues = [];
            $colValues['id_stud'] = $student->id_stud;
            $colValues['firstName'] = $student->firstName;
            $colValues['middleName'] = $student->middleName;
            $colValues['lastName'] = $student->lastName;
            $colValues['email'] = $student->email;

            $anketaData = json_decode($student->anketa, true);
            // var_dump($anketaData); exit('1');
            if ($anketaData) {
                
                $cellviews=$anketa->cellview($blank, ['anketa' => $anketaData]);
                // var_dump($cellviews); exit('1');
                
                foreach ($cellviews as $elm) {
                    // var_dump($elm); // continue;
                    if(!isset($elm['name'])){
                        continue;
                    }
                    if ($elm['teg'] == 'file') {
                        $colValues[$elm['name']] = '<a href="' . basename($elm['value']) . '">' . basename($elm['value']) . '</a>';
                        $files[] = $elm['path'];
                    } else {
                        $colValues[$elm['name']] = $elm['html'];
                    }
                }
            }
            // exit('2');
            // var_dump($colValues); exit('1');
            $rows[] = $colValues;
        }


        
        
        // ============= create html = begin ===================================
        $html = "<!DOCTYPE html>
            <html>
            <head><meta charset=\"utf-8\"></head>
            <body>
            <h1>{$kurs->name_kurs}</h1>
            <h2>{$group->name_group} {$group->date_start}</h2>
            <table>
            ";

        $html.="<thead><tr>";
        foreach ($colNames as $colName) {
            $html.="<th>" . htmlspecialchars($colName) . "</th>";
        }
        $html.="</tr></thead>";

        $html.="<tbody>";
        foreach ($rows as $row) {
            $html.="<tr>";
            foreach ($colNames as $colKey => $colName) {
                $html.="<td>" . (isset($row[$colKey]) ? $row[$colKey] : '') . "</td>";
            }
            $html.="</tr>";
        }
        $html.="</tbody>";
        $html.="</table></body></html>";
        file_put_contents($table, $html);
        // ============= create html = end =====================================
        
        //        
        //        // ============= create csv = begin ====================================
        //        $fp = fopen($csv, 'w');
        //
        //        fputcsv($fp, $colNames);
        //        
        //        foreach ($rows as $row) {
        //            $csvrow=[];
        //            foreach ($colNames as $colKey => $colName) {
        //                $val=(isset($row[$colKey]) ? $row[$colKey] : '');
        //                if(preg_match("/^<a /",$val)){
        //                    $csvrow[]='=HYPERLINK("'.strip_tags($val).'")';
        //                }else{
        //                    $csvrow[]= strip_tags($val);
        //                }
        //            }
        //            fputcsv($fp, $csvrow);
        //        }
        //
        //        fclose($fp);
        //
        //        // ============= create csv = end ======================================

        $zip = new \ZipArchive();
        
        $prefix="group{$group->id_group}/";

        if ($zip->open($destination, \ZIPARCHIVE::CREATE) !== true) {
            return false;
        }

        $zip->addFile($table, $prefix.basename($table));
        //$zip->addFile($csv);
        foreach ($files as $thefile) {
            $f=Yii::getAlias("@webroot/uploads/{$thefile}");
            if(is_file($f) && file_exists($f)){
                $zip->addFile($f, $prefix.basename($f));
            }
        }
        $zip->close();

        $url = Yii::getAlias("@web/uploads/kurs{$kurs->id_kurs}/group{$group->id_group}.zip");

        //header('Content-Description: File Transfer');
        //header('Content-Type: application/octet-stream');
        //header('Content-Transfer-Encoding: binary');
        //header('Content-Disposition: attachment; filename=' . basename($destination));
        //header('Expires: 0');
        //header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
        //header('Pragma: public');
        // header('Content-Length: ' . filesize($destination));
        header('Location:' . $url);
        exit();
        //return $url;
    }

    public function actionReminder($id_group) {
        // find group
        $group = Group::findOne($id_group);
        if (!$group || !$group->visible) {
            throw new NotFoundHttpException(Yii::$app->lang->t('Page not found'));
        }
        if ($group->isExpired()) {
            throw new NotFoundHttpException(Yii::$app->lang->t('Page not found'));
        }
        $kurs = $group->idKurs;
        if (!$kurs || !$kurs->visible) {
            throw new NotFoundHttpException(Yii::$app->lang->t('Page not found'));
        }


        $message = '';
        $post = Yii::$app->request->post();
        if (isset($post['email'])) {
            // find student by email
            $student = Student::find()->where(['id_group' => $id_group, 'email' => $post['email']])->one();
            if ($student) {
                // create new secret code
                $student->secret_code = Yii::$app->security->generateRandomString(48);
                $student->save();
                // mail the secret URL
                $kurs = $group->idKurs;
                Yii::$app->mailer->compose(
                                '@app/mail/registration/reminder.php', [
                            'group' => $group,
                            'student' => $student,
                            'kurs' => $kurs
                        ])
                        ->setFrom(Yii::$app->params['adminEmail'])
                        ->setTo($student->email)
                        ->setSubject(Yii::$app->lang->t("{siteName}: registration to {name_kurs}",['siteName'=>Yii::$app->params['siteName'],'name_kurs'=>$kurs->name_kurs]) )
                        ->send();
                $message = Yii::$app->lang->t("Secure link posted to {email}",['email'=>$post['email']]);
                return $this->render('reminder-success', [
                    'group' => $group,
                    'kurs' => $group->idKurs,
                    'message' => $message
                ]);
            } else {

views/group/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Group */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="group-form">

    <?php $form = ActiveForm::begin(); ?>

    
    <?=$form->field($model, 'id_kurs')->dropDownList($kursOptions, [])?>

    <?= $form->field($model, 'name_group')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'date_start')->textInput() ?>

    <?= $form->field($model, 'max_count_stud')->textInput() ?>

    <?= $form->field($model, 'visible')->checkbox() ?>

    <?= $form->field($model, 'anketa')->textarea(['rows' => 6]) ?>
    <p><?=Yii::$app->lang->t('group_anketa_manual')?></p>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::$app->lang->t('Create') : Yii::$app->lang->t('Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/group/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\GroupSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="group-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_group') ?>

    <?= $form->field($model, 'id_kurs') ?>

    <?= $form->field($model, 'name_group') ?>

    <?= $form->field($model, 'date_start') ?>

    <?= $form->field($model, 'max_count_stud') ?>

    <?php // echo $form->field($model, 'visible')->checkbox() ?>

    <?php // echo $form->field($model, 'anketa') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::$app->lang->t('Find'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::$app->lang->t('Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/group/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Group */
$this->title = Yii::$app->lang->t('Create group');
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kursy'), 'url' => ['/kurs/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kurs {name_kurs}',['name_kurs'=>($kurs?$kurs->name_kurs:'')]), 'url' => ['/kurs/view', 'id'=>$model->id_kurs]];
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Groups'), 'url' => ['index', 'id_kurs'=>$model->id_kurs]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="group-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'kursOptions' => $kursOptions,
    ]) ?>

</div>

views/group/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\GroupSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::$app->lang->t('Groups');
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kurs list'), 'url' => ['/kurs/index']];
$this->params['breadcrumbs'][] = ['label' => ($kurs ? $kurs->name_kurs : '') . '"', 'url' => ['/kurs/view', 'id' => ($kurs ? $kurs->id_kurs : '')]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="group-index">

    <h1><?= Html::encode($this->title) ?> <?= Html::a(Yii::$app->lang->t('Create'), ['create', 'id_kurs' => $kurs->id_kurs], ['class' => 'btn btn-success btn-xs']) ?></h1>


    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{registration}&nbsp;{students}&nbsp;{view}&nbsp;{update}&nbsp;&nbsp;{delete}',
                'buttons' => [
                    'registration' => function ($url, $model, $key) {
                        return '<b>' . Html::a(' <span class="glyphicon glyphicon-heart"></span> ', ['/student/registration', 'id_group' => $model['id_group']], ['title' => Yii::$app->lang->t('Registration')]) . '</b>';
                    },
                    'students' => function ($url, $model, $key) {
                        return '<b>' . Html::a(' <span class="glyphicon glyphicon-user"></span> ', ['/student/index', 'id_group' => $model['id_group']], ['title' => Yii::$app->lang->t('Members')]) . '</b>';
                    },
                    'view' =>  function ($url, $model, $key) {
                        return '<b>' . Html::a(' <span class="glyphicon glyphicon-eye-open"></span> ', ['view', 'id' => $model['id_group']], ['title' => Yii::$app->lang->t('View')]) . '</b>';
                    },
                    'update' =>  function ($url, $model, $key) {
                        return '<b>' . Html::a(' <span class="glyphicon glyphicon-pencil"></span> ', ['update', 'id' => $model['id_group']], ['title' => Yii::$app->lang->t('Update')]) . '</b>';
                    },
                    'delete' =>  function ($url, $model, $key) {
                        return '<b>' . Html::a(' <span class="glyphicon glyphicon-trash"></span> ', 
                                               ['delete', 'id' => $model['id_group']], [
                                                'class' => ' ',
                                                'data' => [
                                                    'confirm' => Yii::$app->lang->t('Confirm removal'),
                                                    'method' => 'post',
                                                ]
                                               ] ).'</b>';
                    },
                ]
             ],
             [
                 'attribute'=>'id_group',
                 'label'=>Yii::$app->lang->t('Code'),
                 'filterOptions' => ['class' => 'filterId'],
             ],
            // 'id_kurs',
             [
                 'attribute'=>'name_kurs',
                 'label'=>Yii::$app->lang->t('Course')
             ],
             [
                 'attribute'=>'name_group',
                 'label'=>Yii::$app->lang->t('Group name')
             ],
             [
                 'attribute'=>'date_start',
                 'label'=>Yii::$app->lang->t('Deadline')
             ],
             [
                 'attribute'=>'count_stud',
                 'label'=>Yii::$app->lang->t('NumOfMembers'),
                 'filterOptions' => ['class' => 'filterId'],
             ],
             [
                 'attribute'=>'max_count_stud',
                 'label'=>Yii::$app->lang->t('maxNumOfMembers'),
                 'filterOptions' => ['class' => 'filterId'],
             ],
             [
                 'attribute'=>'visible',
                 'format'=>'boolean',
                 'label'=>Yii::$app->lang->t('isVisible'),
                 'filterOptions' => ['class' => 'filterId'],
             ],
        // 'anketa',
        ],
    ]);
    ?>

</div>

views/group/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Group */


$kurs=$model->idKurs;
$this->title = Yii::$app->lang->t('Update group') . ': ' . $model->id_group;
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kurs list'), 'url' => ['/kurs/index']];
$this->params['breadcrumbs'][] = ['label' => ($kurs?$kurs->name_kurs:''), 'url' => ['/kurs/view', 'id'=>$model->id_kurs]];
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Groups'), 'url' => ['index', 'id_kurs'=>$model->id_kurs]];
$this->params['breadcrumbs'][] = ['label' => $model->id_group, 'url' => ['view', 'id' => $model->id_group]];
$this->params['breadcrumbs'][] = Yii::$app->lang->t('Update');
?>
<div class="group-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'kursOptions' => $kursOptions,
    ]) ?>

</div>

views/group/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Group */
$kurs=$model->idKurs;
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kursy'), 'url' => ['/kurs/index']];
$this->params['breadcrumbs'][] = ['label' => ($kurs?$kurs->name_kurs:''), 'url' => ['/kurs/view', 'id'=>$model->id_kurs]];
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Groups'), 'url' => ['index', 'id_kurs'=>$model->id_kurs]];
$this->title = $model->name_group;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="group-view">

    <h1><?= Html::encode($this->title) ?>

    
        <?= Html::a(Yii::$app->lang->t('Members'), ['/student/index', 'id_group' => $model->id_group], ['class' => 'btn btn-primary btn-xs']) ?>
        <?= Html::a(Yii::$app->lang->t('Registration'), ['/student/registration', 'id_group' => $model->id_group], ['class' => 'btn btn-primary btn-xs']) ?>
        <?= Html::a(Yii::$app->lang->t('Update'), ['update', 'id' => $model->id_group], ['class' => 'btn btn-primary btn-xs']) ?>
        <?= Html::a(Yii::$app->lang->t('Delete'), ['delete', 'id' => $model->id_group], [
            'class' => 'btn btn-danger btn-xs',
            'data' => [
                'confirm' => Yii::$app->lang->t('Delete group confirmation'),
                'method' => 'post',
            ],
        ]) ?>
    </h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_group',
            [                      // the owner name of the model
            'label' => Yii::$app->lang->t('Course'),
            'value' => $kurs->name_kurs,
        ],
            'name_group',
            'date_start',
            'max_count_stud',
            'visible:boolean',
            [
                'label'=> Yii::$app->lang->t('NumOfMembers'),
                'value'=>count($model->students)
            ]
        ],
    ]) ?>

</div>