models/Kurs.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "kurs".
 *
 * @property string $id_kurs
 * @property string $name_kurs
 * @property string $description
 * @property resource $anketa
 * @property boolean $visible
 *
 * @property Group[] $groups
 */
class Kurs extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'kurs';
    }

    public function behaviors() {
        return [
            [
                'class' => \voskobovich\behaviors\ManyToManyBehavior::className(),
                'relations' => [
                    'userIds' => 'users'
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['name_kurs'], 'required'],
            [['description', 'anketa'], 'string'],
            [['visible'], 'boolean'],
            [['name_kurs'], 'string', 'max' => 255],
            [['userIds'], 'each', 'rule' => ['integer']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id_kurs' => Yii::$app->lang->t('id_kurs'),
            'name_kurs' => Yii::$app->lang->t('name_kurs'),
            'description' => Yii::$app->lang->t('description'),
            'anketa' => Yii::$app->lang->t('anketa'),
            'visible' => Yii::$app->lang->t('visible'),
            'userIds'=>Yii::$app->lang->t('userIds')
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroups() {
        return $this->hasMany(Group::className(), ['id_kurs' => 'id_kurs']);
    }
    public function getUsers() {
        return $this->hasMany(User::className(), ['userId' => 'userId'])
                        ->viaTable('user_kurs', ['id_kurs' => 'id_kurs']);
    }

    public function isKursManager(){
        if(Yii::$app->user->isGuest){
            return false;
        }
        if(User::isAdmin()){
            return true;
        }
        // $query=$this->getUsers()->andWhere(['userId'=>Yii::$app->user->identity->userId, 'id_kurs'=>$this->id_kurs]);
        $query=$this->getUsers()->andWhere(['userId'=>Yii::$app->user->identity->userId])->all();
        // var_dump($query);
        // $list=$query->one();
        // exit();
        return count($query)>0;
    }
}

controllers/GroupController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Group;
use app\models\Kurs;
use app\models\GroupSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * GroupController implements the CRUD actions for Group model.
 */
class GroupController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Group models.
     * @return mixed
     */
    public function actionIndex($id_kurs) {
        $kurs = Kurs::findOne($id_kurs);

        if (!$kurs) {
            throw new NotFoundHttpException(Yii::$app->lang->t('Page not found'));
        }

        if(!$kurs->isKursManager()){
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }
        
        $searchModel = new GroupSearch($id_kurs);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


        return $this->render('index', [
                    'searchModel' => $searchModel, 'kurs' => $kurs,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Group model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id) {
        $group=$this->findModel($id);
        $kurs=$group->idKurs;
        if(!$kurs->isKursManager()){
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }

        return $this->render('view', [
            'model' => $group,
        ]);
    }

    /**
     * Creates a new Group model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id_kurs) {
        $kurs = Kurs::findOne($id_kurs);

        if (!$kurs) {
            throw new NotFoundHttpException(Yii::$app->lang->t('Page not found'));
        }

        if(!$kurs->isKursManager()){
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }
        $model = new Group();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_group]);
        } else {

            $kursOptions = ArrayHelper::map(Kurs::find()->all(), 'id_kurs', 'name_kurs');

            return $this->render('create', [
                        'model' => $model,
                        'kursOptions' => $kursOptions,
                        'kurs' => $kurs
            ]);
        }
    }

    /**
     * Updates an existing Group model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $group = $this->findModel($id);
        $kurs=$group->idKurs;
        if(!$kurs->isKursManager()){
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }

        if ($group->load(Yii::$app->request->post()) && $group->save()) {
            return $this->redirect(['view', 'id' => $group->id_group]);
        } else {
            $kursOptions = ArrayHelper::map(Kurs::find()->all(), 'id_kurs', 'name_kurs');

            return $this->render('update', [
                        'model' => $group,
                        'kursOptions' => $kursOptions
            ]);
        }
    }

    /**
     * Deletes an existing Group model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id) {
        $group = $this->findModel($id);
        $kurs=$group->idKurs;
        if(!$kurs->isKursManager()){
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }
        $group->delete();
        return $this->redirect(['index', 'id_kurs'=>$kurs->id_kurs]);
    }

    /**
     * Finds the Group model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Group the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Group::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

controllers/KursController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Kurs;
use app\models\KursSearch;
use app\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\lib\ArrayHelper;

/**
 * KursController implements the CRUD actions for Kurs model.
 */
class KursController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Kurs models.
     * @return mixed
     */
    public function actionIndex() {

        if (Yii::$app->user->isGuest) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }

        $searchModel = new KursSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (!\app\models\User::isAdmin()) {
            $user = Yii::$app->user->identity;
            $kursIds = array_map(function($m) {
                return $m->id_kurs;
            }, $user->getKurs()->all());
            $dataProvider->query->andWhere(['id_kurs' => $kursIds]);
        }
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all public Kurs models.
     * @return mixed
     */
    public function actionPublic() {
        $searchModel = new KursSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $query = $dataProvider->query;
        $rowsPerPage = Yii::$app->params['rowsPerPage'];
        $query->andWhere(['visible' => 1]);

        $request = array_merge(Yii::$app->request->post(), Yii::$app->request->queryParams);

        $start = isset($request['start']) ? ( (int) $request['start'] ) : 0;
        return $this->render('public', [
                    'searchModel' => $searchModel,
                    'rows' => $query->limit($rowsPerPage)->offset($start)->all(),
                    'request' => $request
        ]);
    }

    /**
     * Displays a single Kurs model.
     * @param string $id
     * @return mixed
     */
    public function actionDetails($id) {
        $kurs = $this->findModel($id);
        if (!$kurs->visible) {
            throw new NotFoundHttpException(Yii::$app->lang->t('Page not found'));
        }
        return $this->render('details', [
                    'model' => $kurs,
        ]);
    }

    /**
     * Displays a single Kurs model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id) {
        $kurs = $this->findModel($id);
        if (!$kurs->isKursManager()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }
        return $this->render('view', [
                    'model' => $kurs,
        ]);
    }

    /**
     * Creates a new Kurs model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        if (!\app\models\User::isAdmin()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin rights required'));
        }
        $model = new Kurs();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_kurs]);
        } else {
            $userOptions = ArrayHelper::map(User::find()->all(), 'userId', ['userPIB', 'userLogin']);
            return $this->render('create', [
                        'model' => $model,
                        'userOptions' => $userOptions,
            ]);
        }
    }

    /**
     * Updates an existing Kurs model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $kurs = $this->findModel($id);
        if (!$kurs->isKursManager()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }
        if ($kurs->load(Yii::$app->request->post()) && $kurs->save()) {
            return $this->redirect(['view', 'id' => $kurs->id_kurs]);
        } else {


            $userOptions = ArrayHelper::map(User::find()->all(), 'userId', ['userPIB', 'userLogin']);
            return $this->render('update', [
                        'model' => $kurs,
                        'userOptions' => $userOptions,
            ]);
        }
    }

    /**
     * Deletes an existing Kurs model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id) {
        $kurs = $this->findModel($id);
        if (!\app\models\User::isAdmin()){
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin rights required'));
        }
        $kurs->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Kurs model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Kurs the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Kurs::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\Kurs;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\lib\ArrayHelper;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex() {
        if (!\app\models\User::isAdmin()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin rights required'));
        }
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        if (!\app\models\User::isAdmin()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin rights required'));
        }
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        if (!\app\models\User::isAdmin()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin rights required'));
        }
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (isset($post['userPassword1']) && isset($post['userPassword2']) && strlen($post['userPassword1']) > 0 && $post['userPassword1'] == $post['userPassword2']) {
                $model->setPassword($post['userPassword1']);
                $model->save();
            }
            return $this->redirect(['view', 'id' => $model->userId]);
        } else {
            $kurses = ArrayHelper::map(Kurs::find()->all(), 'id_kurs', ['name_kurs']);
            return $this->render('create', [
                        'model' => $model,
                        'kurses' => $kurses,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        if (!\app\models\User::isAdmin()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin rights required'));
        }
        $model = $this->findModel($id);

        $post = Yii::$app->request->post();
        if ($model->load($post) && $model->save()) {
            if (isset($post['userPassword1']) && isset($post['userPassword2']) && strlen($post['userPassword1']) > 0 && $post['userPassword1'] == $post['userPassword2']) {
                $model->setPassword($post['userPassword1']);
                $model->save();
            }
            return $this->redirect(['view', 'id' => $model->userId]);
        } else {
            $kurses = ArrayHelper::map(Kurs::find()->all(), 'id_kurs', ['name_kurs']);
            return $this->render('update', [
                        'model' => $model,
                        'kurses' => $kurses,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        if (!\app\models\User::isAdmin()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin rights required'));
        }
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

views/kurs/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Kurs */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="kurs-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name_kurs')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'visible')->checkbox() ?>

    <?php
    if(\app\models\User::isAdmin()){
        echo $form->field($model, 'userIds')->widget(Select2::classname(), [
            'data' => $userOptions,
            'options' => ['placeholder' => Yii::$app->lang->t('Select manager')],
            'pluginOptions' => [
                'allowClear' => true,
                'multiple' => true
            ],
        ]);        
    }
    ?>

    <?= $form->field($model, 'anketa')->textarea(['rows' => 6]) ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::$app->lang->t('Create') : Yii::$app->lang->t('Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/kurs/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\KursSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="kurs-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_kurs') ?>

    <?= $form->field($model, 'name_kurs') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'anketa') ?>

    <?= $form->field($model, 'visible')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::$app->lang->t('Find'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::$app->lang->t('Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/kurs/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Kurs */

$this->title = Yii::$app->lang->t('Create course');
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kursy'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kurs-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'userOptions'=>$userOptions,
    ]) ?>

</div>

views/kurs/details.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Kurs */

$this->title = $model->name_kurs;

if($model->isKursManager()){
    $this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kursy'), 'url' => ['index']];
    $this->params['breadcrumbs'][] = ['label' => $model->name_kurs, 'url' => ['view', 'id' => $model->id_kurs]];
}else{
    $this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kursy'), 'url' => ['public']];
}
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kurs-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= $model->description ?>
    </p>
    <?php
    $groups = $model->getGroups()->andWhere(' visible=1 and date_start > now() ')->all();
    foreach ($groups as $group) {
        // echo '<pre>'; print_r($groups); echo '</pre>';
        echo '<div class="group-item"> ' .Yii::$app->lang->t('Deadline').' '. date(Yii::$app->params['dateFormat'], strtotime($group->date_start))
        . ' ' . Html::a(Yii::$app->lang->t('Signup'), ['/student/registration', 'id_group' => $group->id_group], ['class' => 'btn btn-success btn-xs'])
        . ' ' . 
            ( \Yii::$app->params['allow_corrections']
                ? Html::a(Yii::$app->lang->t('Update profile'), ['/student/reminder', 'id_group' => $group->id_group], ['class' => 'btn btn-primary btn-xs'])
                : '' )
                
        . '</div>';
    }
    ?>
</div>

views/kurs/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\KursSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::$app->lang->t('Kurs list');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kurs-index">

    <h1><?= Html::encode($this->title) ?> <?= Html::a(Yii::$app->lang->t('Create course'), ['create'], ['class' => 'btn btn-success btn-xs']) ?></h1>



    <?php
    if (\app\models\User::isAdmin()) {
        $actionTemplate = '{view}&nbsp;{update}{group}&nbsp;{delete}';
    } else {
        $actionTemplate = '{view}&nbsp;{update}{group}';
    }
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => $actionTemplate,
                'buttons' => [
                    'group' => function ($url, $model, $key) {
                        return '<b>' . Html::a(' <span class="glyphicon glyphicon-user"></span> ', ['group/index', 'id_kurs' => $model->id_kurs], ['title' => Yii::$app->lang->t('Groups')]) . '</b>';
                    }
                ]
            ],
            [
                'attribute' => 'id_kurs',
                'filterOptions' => ['class' => 'filterId'],
            ]
            ,
            'name_kurs',
            [
                'attribute' => 'visible',
                'format'=>'boolean',
                'filterOptions' => ['class' => 'filterId'],
                'filter'=>array(""=>"","1"=>"Yes","0"=>"No")
            ]
        ],
    ]);
    ?>

</div>

views/kurs/public.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\KursSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::$app->lang->t('Kurs list');
$this->params['breadcrumbs'][] = Yii::$app->lang->t('Kurs list');
?>
<div class="kurs-index">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->
    <?php
    
    
    foreach($rows as $row){
        ?><div>
            <h3><?=Html::a($row->name_kurs, ['/kurs/details', 'id' => $row->id_kurs], ['class' => '-'])?></h3>
            <div><?=$row->description?></div>
            <?php
                $now=date('Y-m-d');
                $groups=$row->getGroups()->andWhere(" visible=1 and date_start >= '$now' ")->all();
                foreach($groups as $group){
                    // echo '<pre>'; print_r($groups); echo '</pre>';
                    echo '<div class="group-item">'.$group->name_group.' '.Yii::$app->lang->t('Deadline').' '.date(Yii::$app->params['dateFormat'],strtotime($group->date_start))
                         .' '.Html::a(Yii::$app->lang->t('Signup'), ['/student/registration', 'id_group' => $group->id_group], ['class' => 'btn btn-success btn-xs'])
                         
                         . ( \Yii::$app->params['allow_corrections'] 
                            ? ( ' ' . Html::a(Yii::$app->lang->t('Update profile'), ['/student/reminder', 'id_group' => $group->id_group], ['class' => 'btn btn-primary btn-xs']) )
                            :'')

                        .'</div>';
                }
                
            ?>
        </div><?php
    }
    
    ?>

</div>

views/kurs/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Kurs */

$this->title =  Yii::$app->lang->t('Update {name_kurs}',['name_kurs'=>$model->name_kurs]);
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kursy'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name_kurs, 'url' => ['view', 'id' => $model->id_kurs]];
$this->params['breadcrumbs'][] = Yii::$app->lang->t('Update');
?>
<div class="kurs-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'userOptions'=>$userOptions,
    ]) ?>

</div>

views/kurs/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

\kartik\select2\Select2Asset::register($this);

/* @var $this yii\web\View */
/* @var $model app\models\Kurs */

$this->title = $model->name_kurs;
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kurs list'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kurs-view">

    <h1><?= Html::encode($this->title) ?>
    <?= Html::a(Yii::$app->lang->t('Update'), ['update', 'id' => $model->id_kurs], ['class' => 'btn btn-primary btn-xs']) ?>
        <?= Html::a(Yii::$app->lang->t('Delete'), ['delete', 'id' => $model->id_kurs], [
            'class' => 'btn btn-danger btn-xs',
            'data' => [
                'confirm' => Yii::$app->lang->t('Delete course confirmation'),
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a(Yii::$app->lang->t('Groups'), ['group/index', 'id_kurs' => $model->id_kurs], ['class' => 'btn btn-primary btn-xs']) ?>
    </h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_kurs',
            'name_kurs',
            'description:ntext',
            'visible:boolean',
        ],
    ]) ?>
    <div class="manager"> <h3><?=Yii::$app->lang->t('Admins')?></h3>
        <ol>
        <?php
         $users=$model->getUsers()->all();
         
         foreach($users as $user){
             echo  "<li>".Html::a(" {$user->userLogin}, {$user->userPIB} ", ['user/view', 'id' => $user->userId], ['class' => '', 'target'=>"_blank"]) ."</li>";
         }
        ?> 
        </ol>
    </div>    

    <h3><?=Yii::$app->lang->t('BlankAnkety')?></h3>
    <?php
       $decoded=json_decode($model->anketa,true);
       if($decoded){
           echo "<div style=\"color:green;\">".Yii::$app->lang->t('SyntaxOK')."</div>";
       }else{
           echo "<div style=\"color:red;\">".Yii::$app->lang->t('SyntaxError')."</div>";
       }
    ?>
    <pre><?=htmlspecialchars($model->anketa)?></pre>
    
    
    <?php
    if($decoded){

        $obj = new \app\lib\ShowAnketa('anketa');
        echo "<h3>".Yii::$app->lang->t('BlankAnketyPreview')."</h3>".$obj->form($decoded, []);    
        
        $this->registerCssFile(Yii::getAlias('@web/css/bootstrap-datepicker.min.css'));
        $this->registerJSFile(Yii::getAlias('@web/js/bootstrap-datepicker.min.js'),['depends' => [\yii\web\JqueryAsset::className()]]);
        $this->registerJSFile(Yii::getAlias('@web/js/bootstrap-datepicker.ru.min.js'),['depends' => [\yii\web\JqueryAsset::className()]]);
        $this->registerJSFile(Yii::getAlias('@web/js/showanketa.js'),['depends' => [\yii\web\JqueryAsset::className()]]); 

        $this->registerJs("
            window.alertShown=false;
            window.enableAlertDelayed=function(){window.alertShown=false;};
            $('#studentUpdateForm').submit(function(event){
               if(!anketa.fn.validate()){
                 if(!window.alertShown){
                    alert( '".Yii::$app->lang->t('FillInCorrectData')."' );
                    window.alertShown=true;
                    setTimeout(window.enableAlertDelayed, 1000);
                 }
                 event.preventDefault();
               }
            });
        ");


    }

    ?>
    
</div>