models/Student.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "student".
 *
 * @property string $id_stud
 * @property string $id_group
 * @property string $Fio
 * @property string $email
 * @property string $secret_code
 * @property resource $anketa
 *
 * @property Group $idGroup
 */
class Student extends \yii\db\ActiveRecord
{
    
    public static function getStatusOptions(){
        return [
            ''=>'',
            'new'=>Yii::$app->lang->t('status_new'),
            'rejected'=>Yii::$app->lang->t('status_rejected'),
            'accepted'=>Yii::$app->lang->t('status_accepted')
        ];
    } 
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_group'], 'integer'],
            [['anketa','keyWords','status'], 'string'],
            [['firstName','lastName', 'email'], 'required'],
            [['firstName','lastName','middleName', 'email', 'secret_code'], 'string', 'max' => 255],
            ['email', 'email'],
            [['dateCreated'], 'date', 'format' => 'php:Y-m-d']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_stud' => Yii::$app->lang->t('id_stud'),
            'id_group' => Yii::$app->lang->t('id_group'),
            'firstName' => Yii::$app->lang->t('firstName'),
            'middleName' => Yii::$app->lang->t('middleName'),
            'lastName' => Yii::$app->lang->t('lastName'),
            'email' => Yii::$app->lang->t('email'),
            'secret_code' => Yii::$app->lang->t('secret_code'),
            'anketa' => Yii::$app->lang->t('anketa'),
            'dateCreated'=>Yii::$app->lang->t('dateCreated'),
            'keyWords'=>Yii::$app->lang->t('keyWords'),
            'status'=>Yii::$app->lang->t('status'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdGroup()
    {
        return $this->hasOne(Group::className(), ['id_group' => 'id_group']);
    }
    
    public function getKeyWords(){
        $kw='';

        $group = $this->idGroup;
        $kurs = $group->idKurs;

        $kw.="
            ".Yii::$app->lang->t('Course')." {$kurs->name_kurs}
            ".Yii::$app->lang->t('Group')." {$group->name_group}
            ".Yii::$app->lang->t('firstName')." {$this->firstName}
            ".Yii::$app->lang->t('middleName')." {$this->middleName}
            ".Yii::$app->lang->t('lastName')." {$this->lastName}
            ".Yii::$app->lang->t('email')." {$this->email}
        ";
            
        $obj = new \app\lib\ShowAnketa('anketa');
        $anketaData = json_decode($this->anketa,true);
        if($anketaData){
            $post=['anketa'=> array_map(function($x){return $x['value'];}, $anketaData )];
        }else{
            $post=['anketa'=> []];
        }
        $anketa = $group->blankAnkety();
        $kw.=strip_tags(str_replace('<',' <',$obj->view($anketa, $post)));
        
        $kw = preg_replace("/( |\\t|\n)+/",' ',mb_strtolower($kw,"UTF-8"));
        $kw = preg_replace("/( |\\t|\n)+/",' ',$kw);
        // var_dump($kw); exit();
        return $kw;
    }
}

controllers/GroupController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Group;
use app\models\Kurs;
use app\models\GroupSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * GroupController implements the CRUD actions for Group model.
 */
class GroupController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Group models.
     * @return mixed
     */
    public function actionIndex($id_kurs) {
        $kurs = Kurs::findOne($id_kurs);

        if (!$kurs) {
            throw new NotFoundHttpException(Yii::$app->lang->t('Page not found'));
        }

        if(!$kurs->isKursManager()){
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }
        
        $searchModel = new GroupSearch($id_kurs);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


        return $this->render('index', [
                    'searchModel' => $searchModel, 'kurs' => $kurs,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Group model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id) {
        $group=$this->findModel($id);
        $kurs=$group->idKurs;
        if(!$kurs->isKursManager()){
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }

        return $this->render('view', [
            'model' => $group,
        ]);
    }

    /**
     * Creates a new Group model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id_kurs) {
        $kurs = Kurs::findOne($id_kurs);

        if (!$kurs) {
            throw new NotFoundHttpException(Yii::$app->lang->t('Page not found'));
        }

        if(!$kurs->isKursManager()){
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }
        $model = new Group();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_group]);
        } else {

            $kursOptions = ArrayHelper::map(Kurs::find()->all(), 'id_kurs', 'name_kurs');

            return $this->render('create', [
                        'model' => $model,
                        'kursOptions' => $kursOptions,
                        'kurs' => $kurs
            ]);
        }
    }

    /**
     * Updates an existing Group model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $group = $this->findModel($id);
        $kurs=$group->idKurs;
        if(!$kurs->isKursManager()){
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }

        if ($group->load(Yii::$app->request->post()) && $group->save()) {
            return $this->redirect(['view', 'id' => $group->id_group]);
        } else {
            $kursOptions = ArrayHelper::map(Kurs::find()->all(), 'id_kurs', 'name_kurs');

            return $this->render('update', [
                        'model' => $group,
                        'kursOptions' => $kursOptions
            ]);
        }
    }

    /**
     * Deletes an existing Group model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id) {
        $group = $this->findModel($id);
        $kurs=$group->idKurs;
        if(!$kurs->isKursManager()){
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }
        $group->delete();
        return $this->redirect(['index', 'id_kurs'=>$kurs->id_kurs]);
    }

    /**
     * Finds the Group model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Group the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Group::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

controllers/KursController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Kurs;
use app\models\KursSearch;
use app\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\lib\ArrayHelper;

/**
 * KursController implements the CRUD actions for Kurs model.
 */
class KursController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Kurs models.
     * @return mixed
     */
    public function actionIndex() {

        if (Yii::$app->user->isGuest) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }

        $searchModel = new KursSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (!\app\models\User::isAdmin()) {
            $user = Yii::$app->user->identity;
            $kursIds = array_map(function($m) {
                return $m->id_kurs;
            }, $user->getKurs()->all());
            $dataProvider->query->andWhere(['id_kurs' => $kursIds]);
        }
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all public Kurs models.
     * @return mixed
     */
    public function actionPublic() {
        $searchModel = new KursSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $query = $dataProvider->query;
        $rowsPerPage = Yii::$app->params['rowsPerPage'];
        $query->andWhere(['visible' => 1]);

        $request = array_merge(Yii::$app->request->post(), Yii::$app->request->queryParams);

        $start = isset($request['start']) ? ( (int) $request['start'] ) : 0;
        return $this->render('public', [
                    'searchModel' => $searchModel,
                    'rows' => $query->limit($rowsPerPage)->offset($start)->all(),
                    'request' => $request
        ]);
    }

    /**
     * Displays a single Kurs model.
     * @param string $id
     * @return mixed
     */
    public function actionDetails($id) {
        $kurs = $this->findModel($id);
        if (!$kurs->visible) {
            throw new NotFoundHttpException(Yii::$app->lang->t('Page not found'));
        }
        return $this->render('details', [
                    'model' => $kurs,
        ]);
    }

    /**
     * Displays a single Kurs model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id) {
        $kurs = $this->findModel($id);
        if (!$kurs->isKursManager()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }
        return $this->render('view', [
                    'model' => $kurs,
        ]);
    }

    /**
     * Creates a new Kurs model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        if (!\app\models\User::isAdmin()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin rights required'));
        }
        $model = new Kurs();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_kurs]);
        } else {
            $userOptions = ArrayHelper::map(User::find()->all(), 'userId', ['userPIB', 'userLogin']);
            return $this->render('create', [
                        'model' => $model,
                        'userOptions' => $userOptions,
            ]);
        }
    }

    /**
     * Updates an existing Kurs model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $kurs = $this->findModel($id);
        if (!$kurs->isKursManager()) {
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin/manager rights required'));
        }
        if ($kurs->load(Yii::$app->request->post()) && $kurs->save()) {
            return $this->redirect(['view', 'id' => $kurs->id_kurs]);
        } else {


            $userOptions = ArrayHelper::map(User::find()->all(), 'userId', ['userPIB', 'userLogin']);
            return $this->render('update', [
                        'model' => $kurs,
                        'userOptions' => $userOptions,
            ]);
        }
    }

    /**
     * Deletes an existing Kurs model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id) {
        $kurs = $this->findModel($id);
        if (!\app\models\User::isAdmin()){
            throw new \yii\web\ForbiddenHttpException(Yii::$app->lang->t('Admin rights required'));
        }
        $kurs->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Kurs model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Kurs the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Kurs::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

views/student/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Student */


$this->title = Yii::$app->lang->t('Create');
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kursy'), 'url' => ['/kurs/index']];
$this->params['breadcrumbs'][] = ['label' => $kurs->name_kurs, 'url' => ['/kurs/view', 'id' => $kurs->id_kurs]];
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Groups'), 'url' => ['/group/index', 'id_kurs' => $kurs->id_kurs]];
$this->params['breadcrumbs'][] = ['label' => $group->name_group, 'url' => ['/group/view', 'id' => $group->id_group]];
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Members'), 'url' => ['index', 'id_group' => $group->id_group]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="student-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
        'groupOptions' => $groupOptions,
        'group' => $group,
        'kurs' => $kurs
    ])
    ?>

</div>

views/student/delete-registration-ok.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $student app\models\Student */

$this->title = Yii::$app->lang->t('RegistrationCancelled');
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kursy'), 'url' => ['/kurs/public']];
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kurs {name_kurs}',['name_kurs'=>$kurs->name_kurs]), 'url' => ['/kurs/details', 'id' => $kurs->id_kurs]];
$this->params['breadcrumbs'][] = Yii::$app->lang->t('Group {name_group}',['name_group'=>$group->name_group]) ;
$this->params['breadcrumbs'][] = "{$student->firstName} {$student->middleName} {$student->lastName}";
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="student-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    DetailView::widget([
        'model' => $student,
        'attributes' => [
            //   'id_stud',
            [
                'label' => Yii::$app->lang->t('Course'),
                'value' => $kurs->name_kurs,
            ],
            [
                'label' => Yii::$app->lang->t('id_group'),
                'value' => $group->name_group,
            ],
            [
                'label' => Yii::$app->lang->t('Deadline'),
                'value' => date(Yii::$app->params['dateFormat'], strtotime($group->date_start)),
            ],
            'Fio',
            'email:email',
        //  'secret_code',
        //   'anketa',
        ],
    ])
    ?>

    <?php
    $obj = new \app\lib\ShowAnketa('anketa');
    $post = ['anketa' => array_map(function($x) {
                    return $x['value'];
                }, json_decode($student->anketa, true))];

    $anketa = $group->blankAnkety();
    //return json_encode($anketa);
    echo $obj->view($anketa, $post);
    ?> 

</div>

views/student/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;

use app\models\Student;
/* @var $this yii\web\View */
/* @var $searchModel app\models\StudentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::$app->lang->t('Members');
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kursy'), 'url' => ['/kurs/index']];
$this->params['breadcrumbs'][] = ['label' => ($kurs?$kurs->name_kurs:''), 'url' => ['/kurs/view', 'id'=>$group->id_kurs]];
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Groups'), 'url' => ['/group/index', 'id_kurs'=>$group->id_kurs]];
$this->params['breadcrumbs'][] = ['label' => $group->name_group, 'url' => ['/group/view', 'id' => $group->id_group]];
$this->params['breadcrumbs'][] = $this->title;



$statusOptions=Student::getStatusOptions();

?>
<div class="student-index">
    <h1><?= Html::encode($this->title) ?> 
        <?= Html::a(Yii::$app->lang->t('Add member'), ['create','id_group'=>$group->id_group], ['class' => 'btn btn-success btn-xs']) ?>
    </h1>
    
    
    <div class="student-search">

    <span class="student-search-form">
    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <span class="student-search-elm"><?= $form->field($searchModel, 'status')->dropDownList($statusOptions, []) ?></span>
    <span class="student-search-elm"><?= $form->field($searchModel, 'keyWords') ?></span>
    <span class="student-search-elm"><?= $form->field($searchModel, 'dateCreated') ?></span>
    <span class="student-search-elm" style="width:auto;">
        <label for="studentsearch-datecreated" class="control-label">&nbsp;</label><br>
        <?= Html::submitButton(Yii::$app->lang->t('Find'), ['class' => 'btn btn-primary']) ?>
    </span>
    <input type="hidden" name="id_group" value="<?=htmlspecialchars($group->id_group)?>">
    <?php ActiveForm::end(); ?>
    </span>
    <span class="student-search-form">
    <?php $form = ActiveForm::begin([
        'action' => ['download'],
        'method' => 'get',
    ]); ?>

    <span class="student-search-elm" style="width:auto;">
        <label for="studentsearch-datecreated" class="control-label">&nbsp;</label><br>
        <?= Html::submitButton(Yii::$app->lang->t('Download members'), ['class' => 'btn btn-primary']) ?>
    </span>
            <input type="hidden" name="id_group" value="<?=htmlspecialchars($group->id_group)?>">
            <input type="hidden" name="StudentSearch[keyWords]" value="<?=htmlspecialchars($searchModel->keyWords)?>">
            <input type="hidden" name="StudentSearch[dateCreated]" value="<?=htmlspecialchars($searchModel->dateCreated)?>">
    <?php ActiveForm::end(); ?>
    </span>

</div>
    
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\ActionColumn'],
            [
                 'attribute'=>'id_stud',
                 'label'=>Yii::$app->lang->t('Code'),
                 'filterOptions' => ['class' => 'filterId'],
            ],
            // 'idGroup.name_group',
            // 'idGroup.idKurs.name_kurs',
            'firstName',
            'middleName',
            'lastName',
            'email:email',
            [
                 'attribute'=>'status',
                 'label'=>Yii::$app->lang->t('status'),
                 'filterOptions' => ['class' => 'filterId'],
                 'content'=>function($model, $key, $index, $column) use($statusOptions){
                        return Html::dropDownList(
                                "status[".$model->id_stud."]",
                                $model->status,
                                $statusOptions,[
                                    'class'=>'form-control status-selector',
                                    'data-id-stud' => $model->id_stud
                                ]);
                 }
            ],
            [
                 'attribute'=>'dateCreated',
                 'label'=>Yii::$app->lang->t('dateCreated'),
                 'filterOptions' => ['class' => 'filterId'],
             ],
            // 'secret_code',
            // 'anketa',
        ],
    ]); ?>
<?php $this->registerCssFile(Yii::getAlias('@web/css/bootstrap-datepicker.min.css')); ?>
<?php $this->registerJSFile(Yii::getAlias('@web/js/bootstrap-datepicker.min.js'),['depends' => [\yii\web\JqueryAsset::className()]]); ?>
<?php $this->registerJSFile(Yii::getAlias('@web/js/bootstrap-datepicker.uk.min.js'),['depends' => [\yii\web\JqueryAsset::className()]]); ?>
<?php
   $this->registerJs("
       \$('#studentsearch-datecreated').datepicker({
          format: 'yyyy-mm-dd',
          language:'uk'
       });
       \$('.status-selector').change(function(event){
            var elm=\$(event.currentTarget);
            var newValue = elm.val();
            var idStudent = elm.attr('data-id-stud');
            \$.ajax({
                url: \"index.php?r=student%2Fsetstatus\",
                data:{id_stud:idStudent, status:newValue},
                method:'post',
                context: document.body
            }).done(function() {
                // $( this ).addClass( \"done\" );
            });
       });
   ");
?>
</div>

views/student/registration.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;



\kartik\select2\Select2Asset::register($this);


/* @var $this yii\web\View */
/* @var $group app\groups\Group */
$kurs = $group->idKurs;
if (Yii::$app->user->isGuest) {
    $this->params['breadcrumbs'][] = ['label' =>  ($kurs ? $kurs->name_kurs : ''), 'url' => ['/kurs/details', 'id' => $group->id_kurs]];
} else {
    $this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kurs list'), 'url' => ['/kurs/index']];
    $this->params['breadcrumbs'][] = ['label' => ($kurs ? $kurs->name_kurs : ''), 'url' => ['/kurs/view', 'id' => $group->id_kurs]];
    $this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Groups'), 'url' => ['/group/index', 'id_kurs' => $group->id_kurs]];
    $this->params['breadcrumbs'][] = ['label' => $group->name_group, 'url' => ['/group/view', 'id' => $group->id_group]];
}
$this->title = Yii::$app->lang->t('Registration');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="group-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <h2><?= $kurs->name_kurs ?></h2>
    <p><?= $kurs->description ?></p>
    <p><?= $group->name_group ?></p>
    <p><?=Yii::$app->lang->t('Deadline')?> <?= date(Yii::$app->params['dateFormat'], strtotime($group->date_start)) ?></p>
    <p><?=Yii::$app->lang->t('NumOfMembers')?> <?=$group->getStudents()->count()?> / <?=$group->max_count_stud?></p>

    
    
    <?php
    if($postedAnketaData){
        foreach($postedAnketaData as $pad){
            foreach($pad['errors'] as $err){
                echo "<div class='alert alert-danger'>{$err}</div>";
            }
        }
    }
    ?>
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data','id'=>'studentUpdateForm']]); ?> 
    <?= $form->field($student, 'lastName')->textInput(['maxlength' => true])->label(Yii::$app->lang->t('lastName')."*") ?>
    <?= $form->field($student, 'firstName')->textInput(['maxlength' => true])->label(Yii::$app->lang->t('firstName')."*") ?>
    <?= $form->field($student, 'middleName')->textInput(['maxlength' => true]) ?>


    <?= $form->field($student, 'email')->textInput(['maxlength' => true])->label(Yii::$app->lang->t('email')."*") ?>

    <?php
    $obj = new \app\lib\ShowAnketa('anketa');

    $anketa = $group->blankAnkety();
    //return json_encode($anketa);
    echo $obj->form($anketa, $post);
    ?>
    <br>
    <br>
    <input type='submit' value='<?=Yii::$app->lang->t('Signup')?>' class='btn btn-primary'>

    <?php ActiveForm::end(); ?> 
</div>

<?php $this->registerCssFile(Yii::getAlias('@web/css/bootstrap-datepicker.min.css')); ?>
<?php $this->registerJSFile(Yii::getAlias('@web/js/bootstrap-datepicker.min.js'),['depends' => [\yii\web\JqueryAsset::className()]]); ?>
<?php $this->registerJSFile(Yii::getAlias('@web/js/bootstrap-datepicker.uk.min.js'),['depends' => [\yii\web\JqueryAsset::className()]]); ?>
<?php $this->registerJSFile(Yii::getAlias('@web/js/showanketa.js'),['depends' => [\yii\web\JqueryAsset::className()]]); ?>
<?php
   $this->registerJs("
       window.alertShown=false;
       window.enableAlertDelayed=function(){window.alertShown=false;};
       $('#studentUpdateForm').submit(function(event){
          if(!anketa.fn.validate()){
            if(!window.alertShown){
               alert( '".Yii::$app->lang->t('FillInCorrectData')."' );
               window.alertShown=true;
               setTimeout(window.enableAlertDelayed, 1000);
            }
            event.preventDefault();
          }
       });
   ");
?>

views/student/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $student app\models\Student */



$this->title = Yii::$app->lang->t('Update member').' ' . "{$student->firstName} {$student->middleName} {$student->lastName}";
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Kurs list'), 'url' => ['/kurs/index']];
$this->params['breadcrumbs'][] = ['label' => $kurs->name_kurs, 'url' => ['/kurs/view', 'id' => $kurs->id_kurs]];
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Groups'), 'url' => ['/group/index', 'id_kurs' => $kurs->id_kurs]];
$this->params['breadcrumbs'][] = ['label' => $group->name_group, 'url' => ['/group/view', 'id' => $group->id_group]];
$this->params['breadcrumbs'][] = ['label' => Yii::$app->lang->t('Members'), 'url' => ['index', 'id_group' => $group->id_group]];
$this->params['breadcrumbs'][] = ['label' => "{$student->firstName} {$student->middleName} {$student->lastName}", 'url' => ['view', 'id' => $student->id_stud]];
$this->params['breadcrumbs'][] = Yii::$app->lang->t('Update');
?>
<div class="student-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'student' => $student,
        'groupOptions' => $groupOptions,
        'group' => $group,
        'kurs' => $kurs,
        'anketaData'=>$anketaData
    ])
    ?>

</div>